esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
Vou desligar em
esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
Vou desligar em
esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
Vou desligar em
esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
4. This prints once every 5secs.
5. This prints once every 5secs.
6. This prints once every 5secs.
7. This prints once every 5secs.
Vou desligar em
esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
4. This prints once every 5secs.
Vou desligar em
esta em debug
False
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
4. This prints once every 5secs.
Vou desligar em
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
False
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg

['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg\n']
Traceback (most recent call last):
  File "teste.py", line 52, in <module>
    main()
  File "teste.py", line 40, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 29, in import_pydevd
    import pydevd
ImportError: No module named pydevd
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
True
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Could not connect to localhost: 9135
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "teste.py", line 53, in <module>
    main()
  File "teste.py", line 41, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 31, in import_pydevd
    pydevd.settrace('localhost', port=port, stdoutToServer=True, stderrToServer=True, suspend=suspend)
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1622, in settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1669, in _locked_settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 596, in connect
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
True
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Could not connect to localhost: 9135
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "teste.py", line 53, in <module>
    main()
  File "teste.py", line 41, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 31, in import_pydevd
    pydevd.settrace('localhost', port=port, stdoutToServer=True, stderrToServer=True, suspend=suspend)
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1622, in settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1669, in _locked_settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 596, in connect
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
True
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Could not connect to localhost: 9135
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "teste.py", line 53, in <module>
    main()
  File "teste.py", line 41, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 31, in import_pydevd
    pydevd.settrace('localhost', port=port, stdoutToServer=True, stderrToServer=True, suspend=suspend)
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1622, in settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1669, in _locked_settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 596, in connect
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
True
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Could not connect to localhost: 9135
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "teste.py", line 53, in <module>
    main()
  File "teste.py", line 41, in main
    import_pydevd("/home/george/projects/fleet-control-device/data/server/bundles/teste/debug.txt", 9135, False)
  File "teste.py", line 31, in import_pydevd
    pydevd.settrace('localhost', port=port, stdoutToServer=True, stderrToServer=True, suspend=suspend)
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1622, in settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 1669, in _locked_settrace
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/pydevd.py", line 596, in connect
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 449, in start_client
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
esta em debug
True
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
True
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
Existe sim vai atachar a parada
/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
1. This prints once every 5secs.
2. This prints once every 5secs.
Vou desligar em
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 1767, in pydevd_find_thread_by_id
    pydevd_log(1, "Available: %s\n" % [get_thread_id(t) for t in threads] % thread_id)
TypeError: not all arguments converted during string formatting
1. This prints once every 5secs.
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 1767, in pydevd_find_thread_by_id
    pydevd_log(1, "Available: %s\n" % [get_thread_id(t) for t in threads] % thread_id)
TypeError: not all arguments converted during string formatting
Vou desligar em
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 1767, in pydevd_find_thread_by_id
    pydevd_log(1, "Available: %s\n" % [get_thread_id(t) for t in threads] % thread_id)
TypeError: not all arguments converted during string formatting
['/home/george/projects/fleet-control-device/src/teste', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg']
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 1767, in pydevd_find_thread_by_id
    pydevd_log(1, "Available: %s\n" % [get_thread_id(t) for t in threads] % thread_id)
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/home/george/Downloads/pycharm-professional-2019.2.3/pycharm-2019.2.3/debug-eggs/pydevd-pycharm.egg/_pydevd_bundle/pydevd_comm.py", line 1767, in pydevd_find_thread_by_id
    pydevd_log(1, "Available: %s\n" % [get_thread_id(t) for t in threads] % thread_id)
TypeError: not all arguments converted during string formatting
1. This prints once every 5secs.
2. This prints once every 5secs.
3. This prints once every 5secs.
4. This prints once every 5secs.
5. This prints once every 5secs.
6. This prints once every 5secs.
7. This prints once every 5secs.
8. This prints once every 5secs.
9. This prints once every 5secs.
10. This prints once every 5secs.
11. This prints once every 5secs.
12. This prints once every 5secs.
13. This prints once every 5secs.
14. This prints once every 5secs.
15. This prints once every 5secs.
16. This prints once every 5secs.
17. This prints once every 5secs.
18. This prints once every 5secs.
19. This prints once every 5secs.
20. This prints once every 5secs.
21. This prints once every 5secs.
22. This prints once every 5secs.
23. This prints once every 5secs.
24. This prints once every 5secs.
25. This prints once every 5secs.
26. This prints once every 5secs.
27. This prints once every 5secs.
28. This prints once every 5secs.
29. This prints once every 5secs.
30. This prints once every 5secs.
31. This prints once every 5secs.
32. This prints once every 5secs.
33. This prints once every 5secs.
34. This prints once every 5secs.
35. This prints once every 5secs.
36. This prints once every 5secs.
37. This prints once every 5secs.
38. This prints once every 5secs.
39. This prints once every 5secs.
40. This prints once every 5secs.
41. This prints once every 5secs.
42. This prints once every 5secs.
43. This prints once every 5secs.
44. This prints once every 5secs.
45. This prints once every 5secs.
46. This prints once every 5secs.
47. This prints once every 5secs.
48. This prints once every 5secs.
49. This prints once every 5secs.
50. This prints once every 5secs.
51. This prints once every 5secs.
52. This prints once every 5secs.
53. This prints once every 5secs.
54. This prints once every 5secs.
55. This prints once every 5secs.
56. This prints once every 5secs.
57. This prints once every 5secs.
58. This prints once every 5secs.
